chore

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,223 +1,234 @@
-name: frappe_docker
+version: "3"
+
 services:
   backend:
-    depends_on:
-      configurator:
-        condition: service_completed_successfully
-        required: true
     image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: on-failure
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
     networks:
       default: null
-    volumes:
-    - type: volume
-      source: sites
-      target: /home/frappe/frappe-bench/sites
-      volume: {}
+
   configurator:
-    command:
-    - |
-      ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
-    depends_on:
-      db:
-        condition: service_healthy
-        required: true
-      redis-cache:
-        condition: service_started
-        required: true
-      redis-queue:
-        condition: service_started
-        required: true
-      redis-socketio:
-        condition: service_started
-        required: true
+    image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: none
     entrypoint:
-    - bash
-    - -c
+      - bash
+      - -c
+    command:
+      - >
+        ls -1 apps > sites/apps.txt;
+        bench set-config -g db_passwprd $$DB_PASSWORD;
+        bench set-config -g db_host $$DB_HOST;
+        bench set-config -gp db_port $$DB_PORT;
+        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+        bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO";
+        bench set-config -gp socketio_port $$SOCKETIO_PORT;
     environment:
+      DB_PASSWORD: admin
       DB_HOST: db
       DB_PORT: "3306"
       REDIS_CACHE: redis-cache:6379
       REDIS_QUEUE: redis-queue:6379
       REDIS_SOCKETIO: redis-socketio:6379
       SOCKETIO_PORT: "9000"
-    image: frappe/erpnext:v14
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
     networks:
       default: null
+
+  create-site:
+    image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: none
     volumes:
-    - type: volume
-      source: sites
-      target: /home/frappe/frappe-bench/sites
-      volume: {}
-  db:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+    entrypoint:
+      - bash
+      - -c
     command:
-    - --character-set-server=utf8mb4
-    - --collation-server=utf8mb4_unicode_ci
-    - --skip-character-set-client-handshake
-    - --skip-innodb-read-only-compressed
-    environment:
-      MYSQL_ROOT_PASSWORD: 123456789test
+      - >
+        wait-for-it -t 120 db:3306;
+        wait-for-it -t 120 redis-cache:6379;
+        wait-for-it -t 120 redis-queue:6379;
+        wait-for-it -t 120 redis-socketio:6379;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5;
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
+        bench new-site frontend --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app erpnext --set-default;
+    networks:
+      default: null
+
+  db:
+    image: mariadb:10.6
     healthcheck:
-      test:
-      - CMD-SHELL
-      - mysqladmin ping -h localhost --password=123456789test
+      test: mysqladmin ping -h localhost --password=admin
       interval: 1s
       retries: 15
-    image: mariadb:10.6
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - --character-set-server=utf8mb4
+      - --collation-server=utf8mb4_unicode_ci
+      - --skip-character-set-client-handshake
+      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
+    environment:
+      MYSQL_ROOT_PASSWORD: admin
+    volumes:
+      - db-data:/var/lib/mysql
     networks:
       default: null
-    volumes:
-    - type: volume
-      source: db-data
-      target: /var/lib/mysql
-      volume: {}
+
   frontend:
+    image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: on-failure
     command:
-    - nginx-entrypoint.sh
-    depends_on:
-      backend:
-        condition: service_started
-        required: true
-      websocket:
-        condition: service_started
-        required: true
+      - nginx-entrypoint.sh
     environment:
       BACKEND: backend:8000
-      CLIENT_MAX_BODY_SIZE: 50m
-      FRAPPE_SITE_NAME_HEADER: $$host
-      PROXY_READ_TIMOUT: "120"
+      FRAPPE_SITE_NAME_HEADER: frontend
       SOCKETIO: websocket:9000
       UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
       UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
       UPSTREAM_REAL_IP_RECURSIVE: "off"
-    image: frappe/erpnext:v14
-    networks:
-      default: null
+      PROXY_READ_TIMOUT: 120
+      CLIENT_MAX_BODY_SIZE: 50m
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
     ports:
-    - mode: ingress
-      target: 8080
-      published: "8080"
-      protocol: tcp
-    volumes:
-    - type: volume
-      source: sites
-      target: /home/frappe/frappe-bench/sites
-      volume: {}
+      - 8080:8080
+    networks:
+      default: null
+
   queue-default:
-    command:
-    - bench
-    - worker
-    - --queue
-    - default
-    depends_on:
-      configurator:
-        condition: service_completed_successfully
-        required: true
     image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - worker
+      - --queue
+      - default
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
     networks:
       default: null
-    volumes:
-    - type: volume
-      source: sites
-      target: /home/frappe/frappe-bench/sites
-      volume: {}
+
   queue-long:
-    command:
-    - bench
-    - worker
-    - --queue
-    - long
-    depends_on:
-      configurator:
-        condition: service_completed_successfully
-        required: true
     image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - worker
+      - --queue
+      - long
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
     networks:
       default: null
-    volumes:
-    - type: volume
-      source: sites
-      target: /home/frappe/frappe-bench/sites
-      volume: {}
+
   queue-short:
-    command:
-    - bench
-    - worker
-    - --queue
-    - short
-    depends_on:
-      configurator:
-        condition: service_completed_successfully
-        required: true
     image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - worker
+      - --queue
+      - short
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
     networks:
       default: null
-    volumes:
-    - type: volume
-      source: sites
-      target: /home/frappe/frappe-bench/sites
-      volume: {}
-  redis-cache:
-    image: redis:6.2-alpine
-    networks:
-      default: null
-    volumes:
-    - type: volume
-      source: redis-cache-data
-      target: /data
-      volume: {}
+
   redis-queue:
     image: redis:6.2-alpine
+    deploy:
+      restart_policy:
+        condition: on-failure
+    volumes:
+      - redis-queue-data:/data
     networks:
       default: null
+
+  redis-cache:
+    image: redis:6.2-alpine
+    deploy:
+      restart_policy:
+        condition: on-failure
     volumes:
-    - type: volume
-      source: redis-queue-data
-      target: /data
-      volume: {}
+      - redis-cache-data:/data
+    networks:
+      default: null
+
   redis-socketio:
     image: redis:6.2-alpine
+    deploy:
+      restart_policy:
+        condition: on-failure
+    volumes:
+      - redis-socketio-data:/data
     networks:
       default: null
-    volumes:
-    - type: volume
-      source: redis-socketio-data
-      target: /data
-      volume: {}
+
   scheduler:
-    command:
-    - bench
-    - schedule
-    depends_on:
-      configurator:
-        condition: service_completed_successfully
-        required: true
     image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - schedule
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
     networks:
       default: null
-    volumes:
-    - type: volume
-      source: sites
-      target: /home/frappe/frappe-bench/sites
-      volume: {}
+
   websocket:
-    command:
-    - node
-    - /home/frappe/frappe-bench/apps/frappe/socketio.js
-    depends_on:
-      configurator:
-        condition: service_completed_successfully
-        required: true
     image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - node
+      - /home/frappe/frappe-bench/apps/frappe/socketio.js
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
     networks:
       default: null
-    volumes:
-    - type: volume
-      source: sites
-      target: /home/frappe/frappe-bench/sites
-      volume: {}
-networks:
-  default:
-    name: frappe_docker_default
+
 volumes:
   db-data:
     name: frappe_docker_db-data
@@ -229,16 +240,9 @@ volumes:
     name: frappe_docker_redis-socketio-data
   sites:
     name: frappe_docker_sites
-x-backend-defaults:
-  depends_on:
-    configurator:
-      condition: service_completed_successfully
-  image: frappe/erpnext:v14
-  volumes:
-  - sites:/home/frappe/frappe-bench/sites
-x-customizable-image:
-  image: frappe/erpnext:v14
-x-depends-on-configurator:
-  depends_on:
-    configurator:
-      condition: service_completed_successfully
+  logs:
+    name: frappe_docker_logs
+
+networks:
+  default:
+    name: frappe_docker_default
